#!/usr/bin/env python3
"""One-shot: append live dig hits from duplicate-all protocols+tunnel sweep."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

DIR = Path(__file__).resolve().parent
INTEL = DIR / "intel.jsonl"
now = datetime.now(timezone.utc).isoformat()

hits = [
    {
        "tunnel": "ball_core",
        "layer": 1,
        "author": "@alpinebitch",
        "text": "What ever happened to, fuck it, we ball?",
        "url": "https://x.com/alpinebitch/status/2082509183862317271",
        "likes": 0,
        "views": 11,
        "note": "LIVE open question — reply window",
    },
    {
        "tunnel": "ball_core",
        "layer": 1,
        "author": "@WhiskeyD9R",
        "text": "I'll take em. Fuck it, we ball chat",
        "url": "https://x.com/WhiskeyD9R/status/2082504962295345644",
        "likes": 2,
        "views": 1531,
        "note": "LIVE high views for open reply",
    },
    {
        "tunnel": "ball_core",
        "layer": 1,
        "author": "@marylunablossom",
        "text": "this is going to flop but fuck it we ball",
        "url": "https://x.com/marylunablossom/status/2082502497269133665",
        "likes": 1,
        "views": 53,
        "note": "LIVE flop-anxiety frame",
    },
    {
        "tunnel": "reply_targets_hot",
        "layer": 1,
        "author": "@lukatellli",
        "text": "STILL A WIN-WIN. FUCK IT WE BALL",
        "url": "https://x.com/lukatellli/status/2082485203382218808",
        "likes": 24,
        "views": 1643,
        "note": "HOT host 24 likes",
    },
    {
        "tunnel": "reply_targets_hot",
        "layer": 1,
        "author": "@ch0dbhangra",
        "text": "fuck it we ball",
        "url": "https://x.com/ch0dbhangra/status/2082494518289731923",
        "likes": 7,
        "views": 39,
    },
    {
        "tunnel": "reply_targets_hot",
        "layer": 1,
        "author": "@DemDisaster",
        "text": "I'm so tirreed... but fuck it we ball!!!!!!!",
        "url": "https://x.com/DemDisaster/status/2082482072178848061",
        "likes": 6,
        "views": 57,
    },
    {
        "tunnel": "scihub_freedom",
        "layer": 2,
        "author": "@empireantz_",
        "text": "they killed aaron swartz for redistributing journals free",
        "url": "https://x.com/empireantz_/status/2082502711182827835",
        "likes": 0,
        "views": 7,
        "note": "Aaron Swartz lane LIVE",
    },
    {
        "tunnel": "scihub_freedom",
        "layer": 2,
        "author": "@MagnusPharao",
        "text": "You can get the three research articles free off scihub though.",
        "url": "https://x.com/MagnusPharao/status/2082509551073427841",
        "likes": 0,
    },
    {
        "tunnel": "valhalla_L2",
        "layer": 2,
        "author": "@pease_bruce",
        "text": "Semper Fi … til Valhalla comes",
        "url": "https://x.com/pease_bruce/status/2082493676110991576",
        "likes": 0,
        "note": "SACRED — do not meme spam",
    },
    {
        "tunnel": "build_public_ai",
        "layer": 2,
        "author": "@0rdlibrary",
        "text": "Building in public is the wave.. live streaming AI",
        "url": "https://x.com/0rdlibrary/status/2082508066038149543",
        "likes": 2,
        "views": 175,
    },
    {
        "tunnel": "build_public_ai",
        "layer": 2,
        "author": "@zunair_khan_",
        "text": "Building in public starts today. AI Agents Next.js",
        "url": "https://x.com/zunair_khan_/status/2082498139693765106",
        "likes": 0,
    },
    {
        "tunnel": "proto_daft_punk",
        "layer": 2,
        "author": "@ThatEricAlper",
        "text": "Daft Punk mystery as marketing technique",
        "url": "https://x.com/ThatEricAlper/status/2082510212578087330",
        "likes": 0,
        "views": 224,
        "note": "DAFT PUNK PROTOCOL hit",
    },
    {
        "tunnel": "proto_bangers_only",
        "layer": 2,
        "author": "@SharonFull64364",
        "text": "no filler just banger after banger Stones",
        "url": "https://x.com/SharonFull64364/status/2082506161925038491",
        "likes": 0,
    },
    {
        "tunnel": "proto_hell_on_earth",
        "layer": 1,
        "author": "@1hawa__",
        "text": "hell on earth but we have to pooosh",
        "url": "https://x.com/1hawa__/status/2082510439749955708",
        "likes": 0,
        "note": "HELL ON EARTH + still push energy",
    },
    {
        "tunnel": "proto_scorched_earth",
        "layer": 2,
        "author": "@TommyJoao57",
        "text": "I think the USA needs to go scorched earth.",
        "url": "https://x.com/TommyJoao57/status/2082509713892135324",
        "likes": 0,
        "note": "political frame — careful",
    },
    {
        "tunnel": "proto_beak_mogg",
        "layer": 2,
        "author": "@dingus_sandwich",
        "text": "BANANA TYPE SHIT?? streamer",
        "url": "https://x.com/dingus_sandwich/status/2080479460827041883",
        "likes": 1,
        "views": 45,
    },
    {
        "tunnel": "ball_core_dup",
        "layer": 1,
        "author": "@RutgerDaFandit",
        "text": "The fuck it we ball mentality",
        "url": "https://x.com/RutgerDaFandit/status/2082504694748905925",
        "likes": 0,
        "views": 7,
        "note": "dup-rail catch",
    },
    {
        "tunnel": "proto_neverender",
        "layer": 1,
        "author": "@DemDisaster",
        "text": "fuck it we ball!!!!!!! (dont stop energy)",
        "url": "https://x.com/DemDisaster/status/2082482072178848061",
        "likes": 6,
        "views": 57,
    },
]

with INTEL.open("a", encoding="utf-8") as f:
    for h in hits:
        h["dug_at"] = now
        h["dig"] = "duplicate_all_protocols_and_tunnel"
        f.write(json.dumps(h, ensure_ascii=False) + "\n")

# paste-ready drop sheet for this dig
drop = DIR / "DROP_DUP_PROTOCOLS.md"
lines = [
    "# DROP — LIVE (duplicated protocols + tunnels)",
    f"Generated: `{now}`",
    "",
    "Space 30–90s between posts. Valhalla military posts = sacred, do not meme.",
    "",
    "## L1 — LIVE BALL WINDOWS",
    "",
    "### REPLY · @alpinebitch · open question",
    "- https://x.com/alpinebitch/status/2082509183862317271",
    "```",
    "Still here. Zero dollars. Still dangerous. FUCK IT WE FUCKING BALL.",
    "```",
    "",
    "### REPLY · @WhiskeyD9R · 1.5k views",
    "- https://x.com/WhiskeyD9R/status/2082504962295345644",
    "```",
    "Chat heard. Motion locked. POWERSHELL ME UP. FUCK IT WE BALL.",
    "```",
    "",
    "### REPLY · @lukatellli · HOT (24 likes)",
    "- https://x.com/lukatellli/status/2082485203382218808",
    "```",
    "WIN-WIN confirmed. AND IT DONT STOP. FUCK IT WE FUCKING BALL.",
    "```",
    "",
    "### REPLY · @DemDisaster",
    "- https://x.com/DemDisaster/status/2082482072178848061",
    "```",
    "Tired is a setting not a stop. NEVERENDER. FUCK IT WE BALL.",
    "```",
    "",
    "### REPLY · @marylunablossom",
    "- https://x.com/marylunablossom/status/2082502497269133665",
    "```",
    "flop or not we still showed up. TIL VALHALLA. FUCK IT WE BALL.",
    "```",
    "",
    "## L2 — STRUCTURE / PROTOCOLS",
    "",
    "### REPLY · @empireantz_ · Aaron Swartz",
    "- https://x.com/empireantz_/status/2082502711182827835",
    "```",
    "Long live Sci-hub, long live Aaron Swartz. Knowledge for the broke. FUCK IT WE BALL.",
    "```",
    "",
    "### REPLY · @0rdlibrary · building in public",
    "- https://x.com/0rdlibrary/status/2082508066038149543",
    "```",
    "Building in public. Zero budget. COMPUTAH PROTOCOL online. FUCK IT WE BALL.",
    "```",
    "",
    "### QUOTE · @ThatEricAlper · DAFT PUNK",
    "- https://x.com/ThatEricAlper/status/2082510212578087330",
    "```",
    "DAFT PUNK PROTOCOL. HARDER BETTER FASTER STRONGER. Still shipping silent. FUCK IT WE BALL.",
    "```",
    "",
    "### REPLY · @1hawa__ · hell on earth",
    "- https://x.com/1hawa__/status/2082510439749955708",
    "```",
    "Hell on earth. Still push. HELL ON EARTH PROTOCOL. FUCK IT WE FUCKING BALL.",
    "```",
    "",
    "## DO NOT",
    "",
    "- Meme-spam @pease_bruce Til Valhalla (military sacred register)",
    "- Engage scorched-earth political takes as ball drops",
    "",
    "FUCK IT WE FUCKING BALL. ALL PROTOCOLS DUPLICATED. TUNNEL LIVE.",
    "",
]
drop.write_text("\n".join(lines), encoding="utf-8")
print(f"appended {len(hits)} intel hits")
print(f"drop sheet → {drop}")
